name: LSSign
options:
  deploymentTarget:
    iOS: "17.0"
packages:
  zsign:
    url: https://github.com/xtool-org/zsign
    from: 1.0.0
targets:
  LSSign:
    type: application
    platform: iOS
    sources: [Sources/LSSign]
    dependencies:
      - package: zsign
        product: Zupersign
    entitlements:
      path: Sources/LSSign/LSSign.entitlements
      properties:
        application-identifier: 5GTB5N9N33.app.lemon2974.peach9464
        com.apple.developer.team-identifier: 5GTB5N9N33
        get-task-allow: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.lemon2974.peach9464
        INFOPLIST_FILE: Sources/LSSign/Info.plist
        DEVELOPMENT_TEAM: 5GTB5N9N33
        CODE_SIGN_STYLE: Manual